### ekf config file ###
robot_localization:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false  # ❗️Enable full 3D tracking
    publish_acceleration: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: odometry
    odom0_config: [true, true, true,     # position x, y, z
                   true, true, true,     # orientation roll, pitch, yaw
                   true, true, true,     # velocity x, y, z
                   true, true, true,     # angular velocity roll, pitch, yaw
                   false, false, false]  # acceleration

    imu0: imu
    imu0_config: [false, false, false,   # position (not used)
                  true, true, true,      # orientation roll, pitch, yaw
                  false, false, false,   # linear velocity
                  true, true, true,      # angular velocity roll, pitch, yaw
                  false, false, false]   # acceleration